spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.107.73.217/moti-shop?useTimezone=true&serverTimezone=GMT%2B8
    username: root
    password: GDWS-moti-2021
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true